### ISSUE TITLE
Space in \index{} while matching

### ISSUE THREAD

**Issue by floriandk** [stenskjaer/samewords#11]
```latex
\documentclass{article}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup]{reledmac}

\begin{document}

\beginnumbering
\pstart
\edtext{A}{\Afootnote{a}}\index{A, A}
\pend
\endnumbering


\end{document}
```

breaks off with

```python
Traceback (most recent call last):
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/annotate.py", line 363, in content
    symbol = search_string[position]
IndexError: string index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/samewords", line 11, in <module>
    load_entry_point('samewords', 'console_scripts', 'samewords')()
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/cli.py", line 43, in main
    print(samewords.core.process_document(filename))
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/core.py", line 14, in process_document
    updated_paragraphs = [annotate.critical_note_match_replace_samewords(par) for par in paragraphs]
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/core.py", line 14, in <listcomp>
    updated_paragraphs = [annotate.critical_note_match_replace_samewords(par) for par in paragraphs]
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/annotate.py", line 781, in critical_note_match_replace_samewords
    result = sub_processing(TextSegment(text))
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/annotate.py", line 768, in sub_processing
    context.before, context.after, search_word)
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/annotate.py", line 546, in replace_in_proximity
    right = replace_in_context_list(context_after_list, search_word)
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/annotate.py", line 540, in replace_in_context_list
    chunk = replace_in_string(word, chunk)
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/annotate.py", line 652, in replace_in_string
    updated_replacement = make_replacements(search_word_listed, replacement_string_listed)
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/annotate.py", line 629, in make_replacements
    match_in_replace_list = check_list_match(search_list, replace_list, return_list=[])
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/annotate.py", line 603, in check_list_match
    clean(replace_list[0])):
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/annotate.py", line 476, in clean
    full_macro = macro.complete_macro()
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/annotate.py", line 409, in complete_macro
    + '{' + Brackets(self.input_string, start=position).content + '}'
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/annotate.py", line 325, in __init__
    self.content = self.content(search_string, start, macro)
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/annotate.py", line 375, in content
    raise ValueError("Unbalanced brackets. The provided string terminated before all "
ValueError: Unbalanced brackets. The provided string terminated before all brackets were closed.
```

Removing the space from the `\index`-macro will solve the problem, as will changing the macro to something else, e.g. `\indexx`. Also changing the content to something that wouldn't match, eg. `\index{B, B}`, solves the problem.

**Comment by floriandk** [comment]
Related, I guess:

When the entry in the above example is only `\index{A}`, the result becomes `\index{\sameword{A}}`. This is unfortunate as the index-processors (eg. `makeindex`) will take this as two _different_ entries and sort accordingly. I'd say if possible it would be best if `\index` would be an "exclude macro" by default.

**Comment by stenskjaer** [comment]
I have pushed a solution to this to https://github.com/stenskjaer/samewords/tree/bugfix/issue-11. 

I presume that the expected output you want from that should be
```latex
\documentclass{article}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup]{reledmac}

\begin{document}

\beginnumbering
\pstart
\edtext{\sameword[1]{A}}{\Afootnote{a}}\index{\sameword{A}, \sameword{A}}
\pend
\endnumbering


\end{document}
```
Is that correct?

Would you mind testing the branch?

**Comment by stenskjaer** [comment]
Wait. I didn't understand (read) your last comment. So that is not what you expect.

**Comment by stenskjaer** [comment]
The problem I thought with putting `\index{}` in `exclude_macros` was this:

Take this phrase:
```latex
\edtext{Sortes\index[persons]{Socrates}}{\Afootnote{Socrates B}} dicit: 
Sortes\index[persons]{Sortes} probus
```
Here clearly *Sortes* does not refer to the same person in the two positions. But that doesn't matter because we still have an ambiguous reference no matter who the referent is. So now I have just added `\index{}` to the `exclude_macros`. Silly me...

I have pushed an update where it should match no matter what the content of the index is that you can test.
Same branch.

**Comment by floriandk** [comment]
The updated branch handles the index as I'd think is necessary:
The contents of `\index{}`, `\index[]{}` (from the `index`- and `imakeidx`-packages respectively) are completely ignored when placing the `\sameword{}`-tags. My initial example works fine now.

(I'd also suggest, that you add `\edindex{}` to be handled the same way as `\index{}` by default.)

But the brackets are placed incorrectly in a number of cases.
When `\index` appears within the `\edtext{}`:

```latex
\documentclass{article}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup]{reledmac}

\begin{document}

\beginnumbering
\pstart
A \edtext{A\index{A}}{\Afootnote{A}} B B B
\pend
\endnumbering


\end{document}
```

->

```latex
\documentclass{article}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup]{reledmac}

\begin{document}

\beginnumbering
\pstart
\sameword{A} \edtext{\sameword[1]{A\index{A}}}{\Afootnote{A}} B B B
\pend
\endnumbering


\end{document}
```

and in the beginning of the line

```latex
\documentclass{article}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup]{reledmac}


\begin{document}

\beginnumbering
\pstart
A\index{A} \edtext{A}{\Afootnote{A}} B B B
\pend
\endnumbering


\end{document}
```

->

```latex
\documentclass{article}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup]{reledmac}


\begin{document}

\beginnumbering
\pstart
\sameword{A\index{A} }\edtext{\sameword[1]{A}}{\Afootnote{A}} B B B
\pend
\endnumbering


\end{document}
```

which `reledmac` deems to be two different words.

```latex
\documentclass{article}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup]{reledmac}


\begin{document}

\beginnumbering
\pstart
A \edtext{A}{\Afootnote{A}} B B B A\index{A} A \edtext{A}{\Afootnote{A}}
\pend
\endnumbering


\end{document}
```

->

```latex
\documentclass{article}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup]{reledmac}


\begin{document}

\beginnumbering
\pstart
\sameword{A} \edtext{\sameword[1]{A}}{\Afootnote{A}} B B B \sameword{A\index{A} A\sameword{\sameword{ }}}}\edtext{\sameword[1]{A}}{\Afootnote{A}}
\pend
\endnumbering


\end{document}
```

doesn't compile.

**Comment by floriandk** [comment]
Btw: is it possible to see which branch/revision is currently installed? I keep losing track and `samewords --version` only gives the main version number for them all...

**Comment by stenskjaer** [comment]
Yes, this is right. 

I have changed it such that the sameword command is now closed before the following ignored macros. The change is pushed. 

Another stupid bug, caught by you. Thanks for all the tests!

**Comment by stenskjaer** [comment]
About the branch question: I might want to improve the suggestions for testing to use the git commands in stead of just downloading a zip of a branch. Then it's easier to keep track of which branch you are testing...
