### ISSUE TITLE
thin space \,

### ISSUE THREAD

**Issue by floriandk** [stenskjaer/samewords#26]
Thinspace `\,` in the `\edtext` makes the script abort with

```python
Traceback (most recent call last):
  File "/usr/local/bin/samewords", line 11, in <module>
    load_entry_point('samewords', 'console_scripts', 'samewords')()
  File "~/samewords-issue-24/samewords/cli.py", line 99, in main
    output_content = samewords.core.process_document(filename)
  File "~/samewords-issue-24/samewords/core.py", line 26, in process_document
    chunk = ''.join([run_annotation(par) for par in chunk_pars(chunk)])
  File "~/samewords-issue-24/samewords/core.py", line 26, in <listcomp>
    chunk = ''.join([run_annotation(par) for par in chunk_pars(chunk)])
  File "~/samewords-issue-24/samewords/core.py", line 12, in run_annotation
    words = matcher.annotate()
  File "~/samewords-issue-24/samewords/matcher.py", line 28, in annotate
    edtext_end = entry['data'][1]
IndexError: list index out of range
```

e.g. 

```latex
\documentclass[a5paper]{scrartcl}

\usepackage[series={A},noledgroup,draft]{reledmac}

\begin{document}

\beginnumbering
\pstart
5\,000 letters or 
\edtext{5\,000}{%
	\Afootnote{6\,000}}
words?
\pend
\endnumbering

\end{document}
```

If `\,` is replaced with `\thinspace{}` it works. So it would be easy to circumvent for the user in case it is difficult to fix.

**Comment by stenskjaer** [comment]
I have pushed what I believe to be a fix to this. Can you check out branch `issue-26` when you get the time?

**Comment by floriandk** [comment]
Working well with `\,` and other spacing commands.
This was the only thing to test in this branch as for now, wasn't it?

**Comment by stenskjaer** [comment]
No, not on this one. I have some of the others coming up soon (I hope).
