### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by maieul** [stenskjaer/samewords#37]
Hi,
with Ubuntu 18.4
```
sudo -H pip install samewordspocryphes.wiki (master)$ 
Collecting samewords
  Downloading https://files.pythonhosted.org/packages/14/53/81de9c2452896a09252e26dbb92b98db81258cccbe3fb5fe828fad22eab6/samewords-0.5.3.tar.gz (43kB)
    100% |████████████████████████████████| 51kB 276kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-MmD3VL/samewords/setup.py", line 4, in <module>
        from samewords import __version__
      File "samewords/__init__.py", line 11, in <module>
        import samewords.core
      File "samewords/core.py", line 9
        def run_annotation(input_text: str, method: str = 'annotate') -> str:
                                     ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-MmD3VL/samewords/

```

**Comment by stenskjaer** [comment]
Samewords requires Python3.6 installed, and that should actually be installed in Ubuntu 16.04.
So try with the command `pip3` instead of `pip`.

**Comment by maieul** [comment]
yeah, you are right.  sorry, I am very tired currently.
