### ISSUE TITLE
Problem with running samewords on Minmal example

### ISSUE THREAD

**Issue by cmar057** [stenskjaer/samewords#38]
Uploading the Minimal example edition.tex to the webs ervice produces the error 'Error: list index out of range'

The same error is produced by running samewords locally on edition.tex with this trace:

samewords edition.tex
Traceback (most recent call last):
  File "/usr/local/bin/samewords", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/samewords/cli.py", line 116, in main
    print(samewords.core.process_document(filename, procedure))
  File "/usr/local/lib/python3.6/site-packages/samewords/core.py", line 26, in process_document
    return process_string(content, method=method)
  File "/usr/local/lib/python3.6/site-packages/samewords/core.py", line 32, in process_string
    chunked_content = chunk_doc(content)
  File "/usr/local/lib/python3.6/site-packages/samewords/document.py", line 49, in chunk_doc
    indices.append([indices[-1][-1], len(content)+1])
IndexError: list index out of range

**Comment by stenskjaer** [comment]
Thank you very much. This was an embarrasing mistake. It should be solved now.
