### ISSUE TITLE
Still a problem minimal example

### ISSUE THREAD

**Issue by cmar057** [stenskjaer/samewords#39]
Thanks for the correction but adding the needed '\endnumbering' to edition.tex doesn't solve the problem. Both the web service and the script still return 'index out of range'.

Chris

Traceback (most recent call last):
  File "/usr/local/bin/samewords", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/samewords/cli.py", line 116, in main
    print(samewords.core.process_document(filename, procedure))
  File "/usr/local/lib/python3.6/site-packages/samewords/core.py", line 26, in process_document
    return process_string(content, method=method)
  File "/usr/local/lib/python3.6/site-packages/samewords/core.py", line 32, in process_string
    chunked_content = chunk_doc(content)
  File "/usr/local/lib/python3.6/site-packages/samewords/document.py", line 49, in chunk_doc
    indices.append([indices[-1][-1], len(content)+1])
IndexError: list index out of range

**Comment by stenskjaer** [comment]
I am sorry, but I cannot reproduce the error that you describe.

I saved the following in a file and ran that:
```latex
\documentclass{article}
\usepackage[final]{reledmac}

\begin{document}
\beginnumbering

\pstart
We have a passage of text here, such \edtext{a}{\Afootnote{om. M}} nice
place for a critical note.
\pend

\endnumbering
\end{document}
```

It works for me, both locally and on the web client (http://samewords.stenskjaer.net/).

What did you do?

**Comment by stenskjaer** [comment]
As I haven't heard anythings on this for over half a year, I'm going to close it. Feel free to open it again, if you still encounter a problem.
